# Generated by Django 5.1.4 on 2024-12-30 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_weight', models.FloatField(blank=True, help_text="User's target weight in kilograms", null=True)),
                ('daily_steps', models.PositiveIntegerField(blank=True, help_text='Target number of steps per day', null=True)),
                ('weekly_active_minutes', models.PositiveIntegerField(blank=True, help_text='Target number of active minutes per week', null=True)),
                ('daily_calorie_intake', models.PositiveIntegerField(blank=True, help_text='Target daily calorie intake in kcal', null=True)),
                ('protein_target', models.FloatField(blank=True, help_text='Target protein intake in grams per day', null=True)),
                ('carb_target', models.FloatField(blank=True, help_text='Target carbohydrate intake in grams per day', null=True)),
                ('fat_target', models.FloatField(blank=True, help_text='Target fat intake in grams per day', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text="User's current weight in kilograms")),
                ('height', models.FloatField(help_text="User's height in centimeters")),
                ('age', models.PositiveIntegerField(help_text="User's age in years")),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text="User's gender", max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
