# Generated by Django 5.1.4 on 2024-12-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessactivity',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
