# Generated by Django 5.1.4 on 2024-12-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_fitnessactivity_calories_meal_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessactivity',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
